### ISSUE TITLE
Update to version 2.2.0

### ISSUE THREAD

**Issue by jzeferino** [jamesmontemagno/CircleImageView-Xamarin.Android#7]
@jamesmontemagno can I PR a update for the version 2.2.0 of original [CircleImageView](https://github.com/hdodenhof/CircleImageView)?

**Comment by jamesmontemagno** [comment]
yup, go for it.

**Comment by jzeferino** [comment]
@jamesmontemagno I will.

**Comment by jzeferino** [comment]
@jamesmontemagno I will. One other thing. Can I add Cake and add the original repo as a git submodule so I can add a script to build the native android library and call Cake then? I ussually do that in my bindings. See [here](https://github.com/jzeferino/Xamarin.Android.SwitchButton).

**Comment by jamesmontemagno** [comment]
sure
